# Default values for backstage helm chart
replicaCount: 1

# Image configuration
image:
  repository: roadiehq/community-backstage-image
  tag: latest
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 7000

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: backstage.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 512Mi

# Node selector, tolerations, and affinity settings
nodeSelector: {}
tolerations: []
affinity: {}

serviceAccount:
  create: true
  name: ""  # Use default generated name via template


# Environment variables for Backstage
env:
  NODE_ENV: production
  BACKSTAGE_BACKEND_LOG_LEVEL: info

# Backstage configuration
backstage:
  appConfig:
    app:
      title: Backstage
      baseUrl: http://localhost:7000
    backend:
      baseUrl: http://localhost:7000
      listen:
        port: 7000
      database:
        client: pg
        connection:
          host: '{{ printf "%s-postgresql" .Release.Name | quote }}'
          port: 5432
          user: backstage
          password: '${POSTGRES_PASSWORD}'
    auth:
      environment: development
      providers: {} 

# PostgreSQL subchart configuration
postgresql:
  enabled: true
  auth:
    username: backstage
    password: backstage123
    database: backstage
  primary:
    persistence:
      enabled: true
      size: 1Gi
  
# Feature flags for conditional usage
features:
  enablePostgres: true

# Hook settings
hooks:
  preInstall:
    enabled: false
  postInstall: 
    enabled: false
  preUpgrade:
    enabled: false
  postUpgrade:
    enabled: false
  preRollback:
    enabled: false
  postRollback:
    enabled: false
    
# Probes toggles
probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
