name: "backstage"
version: "0.1.0"
usage: "Tools for working with Backstage Helm releases"
description: |-
  This plugin provides additional functionality for managing Backstage Helm releases.
  
  Available Commands:
    - backstage-health: Check the health of a Backstage deployment
    
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/backstage.sh"
hooks:
  install: "cd $HELM_PLUGIN_DIR && chmod +x backstage.sh"
  update: "cd $HELM_PLUGIN_DIR && chmod +x backstage.sh"