name: Release Helm Chart with GPG Signing and OCI Push

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git Identity
        run: |
          git config user.name "1moses1"
          git config user.email "iradukundam47@gmail.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.14.3

      - name: Import GPG Public Key
        run: echo "$GPG_PK" | gpg --batch --import
        env:
          GPG_PK: ${{ secrets.GPG_PK }}

      - name: Prepare GPG Private Keyring for Signing
        run: |
          mkdir -p .cr-gpg
          echo "$SECRING_BASE64" | base64 -d > .cr-gpg/secring.gpg
          echo "$GPG_PASSPHRASE" > .cr-gpg/passphrase
          echo "CR_KEYRING=$(pwd)/.cr-gpg/secring.gpg" >> $GITHUB_ENV
          echo "CR_PASSPHRASE_FILE=$(pwd)/.cr-gpg/passphrase" >> $GITHUB_ENV
        env:
          SECRING_BASE64: ${{ secrets.SECRING_BASE64 }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Update Chart Version from Tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          yq eval ".version = \"$VERSION\"" -i backstage-helm-chart/Chart.yaml
          echo "Updated Chart.yaml version to $VERSION"

      - name: Package Helm Chart (unsigned for now)
        run: |
          mkdir -p .cr-release-packages
          helm dependency update backstage-helm-chart || true
          helm package backstage-helm-chart \
            --destination .cr-release-packages
        # Signing is commented out until key error is resolved
        #     --sign \
        #     --key "$CR_KEY" \
        #     --keyring "$CR_KEYRING"
        env:
          CR_KEY: ${{ secrets.CR_KEY }}

      - name: Upload Helm Chart Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart-signed
          path: .cr-release-packages/*.tgz

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.PAT }}
          CR_KEY: ${{ secrets.CR_KEY }}
          CR_SIGN: false  # signing temporarily disabled
          CR_SKIP_EXISTING: true  # avoid skipping due to previously released tag
          CR_MARK_AS_LATEST: true
