name: Release Helm Chart with chart-releaser

on:
  workflow_dispatch:
  release:
    types: [published]
# on:
#   push:
#     tags:
#       - 'v*'
#     branches:
#       - main

jobs:
  release-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    env:
      GPG_NAME: "1moses1"
      GPG_EMAIL: "iradukundam47@gmail.com"
      CHART_DIR: "charts"
      YQ_VERSION: "v4.40.5"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git Identity
        run: |
          git config user.name "${{ env.GPG_NAME }}"
          git config user.email "${{ env.GPG_EMAIL }}"

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.14.3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq gnupg2 curl coreutils pinentry-curses 
          sudo wget https://github.com/mikefarah/yq/releases/download/${{ env.YQ_VERSION }}/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          ORAS_VERSION="1.1.0"
          curl -LO https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_amd64.tar.gz
          tar -zxvf oras_${ORAS_VERSION}_linux_amd64.tar.gz
          sudo mv oras /usr/local/bin/oras

      - name: Update Chart Version from Tag
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            CLEAN_VERSION=$(echo "$VERSION" | sed -E 's/^backstage-//')
            echo "Setting version to $CLEAN_VERSION"
            yq eval ".version = \"$CLEAN_VERSION\"" -i "$CHART_DIR/Chart.yaml"
          else
            echo "Skipping Chart version update; not a tag push."
          fi

      - name: Auto-generate GPG Key and Prepare Environment
        id: gpg_setup
        run: |
          export GNUPGHOME="$(mktemp -d)"
          echo "GNUPGHOME_PATH=$GNUPGHOME" >> $GITHUB_OUTPUT
          
          gpg --batch --passphrase '' --quick-gen-key "${{ env.GPG_NAME }} <${{ env.GPG_EMAIL }}>" rsa4096 sign 1d

          gpg --export-secret-keys -o "$GNUPGHOME/pubring.gpg"
          gpg --export-secret-keys -o "$GNUPGHOME/secring.gpg"

          mkdir -p .cr-gpg
          cp "$GNUPGHOME/secring.gpg" .cr-gpg/secring.gpg
          cp "$GNUPGHOME/pubring.gpg" .cr-gpg/pubring.gpg

          mkdir -p ~/.gnupg
          cp "$GNUPGHOME/secring.gpg" ~/.gnupg/secring.gpg
          cp "$GNUPGHOME/pubring.gpg" ~/.gnupg/pubring.gpg

          # Export public key directly while GNUPGHOME is valid
          VERSION=${GITHUB_REF#refs/tags/}
          PUBLIC_KEY_NAME="public-key-${VERSION}.asc"
          gpg --homedir "$GNUPGHOME" --armor --export "${{ env.GPG_EMAIL }}" > "public-key-${VERSION}.asc"

        env:
          GPG_NAME: ${{ env.GPG_NAME }}
          GPG_EMAIL: ${{ env.GPG_EMAIL }}

      - name: Debug .cr-gpg
        run: ls -la .cr-gpg

      - name: Move .cr-gpg and Chart.yaml to templates
        run: |
          cp -rf .cr-gpg "$CHART_DIR/templates"

      - name: Characteristics for .cr-gpg/secring.gpg
        run: |
          wc "$CHART_DIR/templates/.cr-gpg/secring.gpg"

      - name: Auto-detect subchart repositories
        run: |
          for dir in $(ls -d ${CHART_DIR}/*/ 2>/dev/null || true); do
            helm dependency list "$dir" 2>/dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Add Bitnami Helm repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          
      - name: Dependency update
        run: |
          cd "$CHART_DIR"
          helm dependency update

      - name: Copy Chart.yaml inside the templates/
        run: |
          cp charts/Chart.yaml charts/templates/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.PAT }}"
          CR_KEY: "${{ env.GPG_EMAIL }}"
          CR_SIGN: true
          CR_SKIP_EXISTING: true

      # - name: Archive and push public.asc to branches
      #   if: github.event_name == 'release'
      #   run: |
      #     git config --global user.name "${{ env.GPG_NAME }}"
      #     git config --global user.email "${{ env.GPG_EMAIL }}"
      #     VERSION=${GITHUB_REF#refs/tags/}
      #     PUBLIC_KEY_NAME="public-key-${VERSION}.asc"

      #     git clone https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }} repo
      #     cd repo

      #     # === Update main branch ===
      #     git checkout main
      #     cp ../"$PUBLIC_KEY_NAME" .
      #     git add "$PUBLIC_KEY_NAME"
      #     git commit -m "chore: archive $PUBLIC_KEY_NAME for release $VERSION" || echo "No changes to commit on main"
      #     git push origin main

      #     # === Update gh-pages branch ===
      #     git checkout gh-pages
      #     cp ../"$PUBLIC_KEY_NAME" .
      #     git add "$PUBLIC_KEY_NAME"
      #     git commit -m "chore: archive $PUBLIC_KEY_NAME for release $VERSION" || echo "No changes to commit on gh-pages"
      #     git push origin gh-pages
      #   shell: bash

      - name: Upload versioned public.asc to release assets
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release'
        with:
          files: public-key-${{ github.ref_name }}.asc
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
