name: Release Helm Chart with Cosign (OCI)

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  # Required for keyless signing with OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git Identity
        run: |
          git config user.name "1moses1"
          git config user.email "iradukundam47@gmail.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.14.3

      - name: Set up Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Authenticate to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | helm registry login ghcr.io -u 1moses1 --password-stdin

      - name: Authenticate Cosign to GHCR via Docker
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u 1moses1 --password-stdin

      - name: Update Chart Version from Tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          yq eval ".version = \"$VERSION\"" -i backstage-helm-chart/Chart.yaml
          echo "Updated Chart.yaml version to $VERSION"

      - name: Save and Push to OCI Registry
        run: |
          helm package backstage-helm-chart
          helm push backstage-*.tgz oci://ghcr.io/1moses1/charts

      - name: Cosign Sign OCI Helm Chart
        run: |
          CHART_REF="ghcr.io/1moses1/charts/backstage:${GITHUB_REF#refs/tags/}"
          cosign sign --yes $CHART_REF
