apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backstage.fullname" . }}-post-upgrade
  annotations:
    # This is a post-upgrade hook
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "backstage.fullname" . }}-post-upgrade
    spec:
      restartPolicy: Never
      containers:
        - name: cache-clear
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
          - |
            echo "Post-upgrade hook: Clearing caches"
            # Simulating cache clearing operation
            sleep 3
            echo "Cache cleared successfully"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgresql.auth.database }}