apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backstage.fullname" . }}-pre-rollback
  annotations:
    # This is a pre-rollback hook
    "helm.sh/hook": pre-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "backstage.fullname" . }}-pre-rollback
    spec:
      restartPolicy: Never
      containers:
        - name: snapshot-db
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
          - |
            echo "Pre-rollback hook: Creating database snapshot"
            # Simulating database snapshot creation
            sleep 5
            echo "Database snapshot created successfully"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgresql.auth.database }}