apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backstage.fullname" . }}-pre-install-db-migration
  annotations:
    # This is a pre-install hook
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      name: {{ include "backstage.fullname" . }}-pre-install-db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: db-migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args:
          - |
            echo "Pre-install hook: Setting up database schema"
            # Simulating database migration/initialization
            sleep 5
            echo "Database migration completed successfully"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: {{ .Values.postgresql.auth.database }}